recovery: set LOCAL_PACK_MODULE_RELOCATIONS := false
Set for all required modules

Caused:
ERROR: ELF file is not a shared object
ERROR: Failed to load as ELF
ERROR: xxxx    failed to pack/unpack file

Change-Id: I3f69d83e6957043297715edf9dbb47d81691a182